# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
	:inetRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.1', 	adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
	:centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', 	adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.255.5', 	adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "off1_rtr"},
                   {ip: '192.168.255.9', 	adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "off2_rtr"},
                   {ip: '192.168.0.1', 	 	adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "cntrl_dir"},
                   {ip: '192.168.0.33',  	adapter: 6, netmask: "255.255.255.240", virtualbox__intnet: "cntrl_hrd"},
                   {ip: '192.168.0.65',  	adapter: 7, netmask: "255.255.255.192", virtualbox__intnet: "cntrl_wf"},
                ]
  },  
	:centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', 		adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "cntrl_dir"},
                ]
  },
	:office1Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.6', 	adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "off1_rtr"},
                   {ip: '192.168.2.1', 		adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "off1_dev"},
                   {ip: '192.168.2.65', 	adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "off1_tst"},
                   {ip: '192.168.2.129', 	adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "off1_mng"},
                   {ip: '192.168.2.193', 	adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "off1_hrd"},
                ]
  },  
	:office1Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.2.66', 	adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "off1_tst"},
                ]
  },
 	:office2Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.10', 	adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "off2_rtr"},
                   {ip: '192.168.1.1', 		adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "off2_dev"},
                   {ip: '192.168.1.129', 	adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "off2_tst"},
                   {ip: '192.168.1.193', 	adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "off2_hrd"},
                ]
  },  
	:office2Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.1.130', 	adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "off2_tst"},
                ]
  },
  
}
Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        
		box.vm.provider :virtualbox do |box|
          box.customize ["modifyvm", :id, "--cpus", "1"]
          box.customize ["modifyvm", :id, "--memory", "256"]
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
			ip r add 192.168.0.0/22 via 192.168.255.2 dev eth1
            SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            ip r add default 		via 192.168.255.1 	dev eth1
            ip r add 192.168.2.0/24 via 192.168.255.6 	dev eth2
            ip r add 192.168.1.0/24 via 192.168.255.10 	dev eth3			
            systemctl restart network
            SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			ip r add default 		via 192.168.0.1 	dev eth1
            systemctl restart network
            SHELL
        when "office1Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.5" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            ip r add default 		via 192.168.255.5 	dev eth1
            systemctl restart network
            SHELL
        when "office1Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			ip r add default 		via 192.168.2.65 	dev eth1
            systemctl restart network
            SHELL
        when "office2Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            ip r add default 		via 192.168.255.9 	dev eth1
            systemctl restart network
            SHELL
        when "office2Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.1.129" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			ip r add default 		via 192.168.1.129 	dev eth1
            systemctl restart network
            SHELL
        end

      end

  end
  
  
end