# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "log-server" do |nfss| 
    # shared folders
	#nfss.vm.synced_folder ".", "/vagrant", type: "virtualbox"

#	nfss.vm.provision "file", source: "srv-rsyslogd.pp", destination: "srv-rsyslogd.pp"
#	nfss.vm.provision "file", source: "srv-inimfile.pp", destination: "srv-inimfile.pp"
	nfss.vm.provision "file", source: "my-rsyslogd.pp", destination: "my-rsyslogd.pp"
	nfss.vm.provision "file", source: "my-inimfile.pp", destination: "my-inimfile.pp"
    nfss.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    nfss.vm.hostname = "log-server"
	nfss.vm.provision "shell", path: "server.sh"	
    nfss.vm.provision "shell", inline: <<-SHELL
		echo "***********************************************************************"
		ls -la my-rsyslogd.pp
		ls -la my-inimfile.pp	
		echo "***********************************************************************"
		semodule -i /home/vagrant/my-rsyslogd.pp
		semodule -i /home/vagrant/my-inimfile.pp
		systemctl restart rsyslog 
	
        #mkdir -p ~root/.ssh
        #cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
  end

  config.vm.define "log-client" do |nfsc|
    nfsc.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
	nfsc.vm.provision "file", source: "my-rsyslogd.pp", destination: "my-rsyslogd.pp"
	nfsc.vm.provision "file", source: "my-inimfile.pp", destination: "my-inimfile.pp"
    nfsc.vm.hostname = "log-client"
    # shared folders
#	nfsc.vm.synced_folder ".", "/vagrant", type: "virtualbox"     
    nfsc.vm.provision "shell", path: "client.sh"
	nfsc.vm.provision "shell", inline: <<-SHELL
		echo "***********************************************************************"
		ls -la my-rsyslogd.pp
		ls -la my-inimfile.pp	
		echo "***********************************************************************"
		semodule -i /home/vagrant/my-rsyslogd.pp
		semodule -i /home/vagrant/my-inimfile.pp
		systemctl restart rsyslog 

		#cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys		
        #mkdir -p ~root/.ssh
        #cp ~vagrant/.ssh/auth* ~root/.ssh
       SHELL
  end

end