# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "control" do |nfss|
    # shared folders
	nfss.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    nfss.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    nfss.vm.hostname = "control"
    nfss.vm.provision "shell", inline: <<-SHELL
		#ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
		yum install epel-release -y && yum install ansible -y
		cp -t  /home/vagrant/.ssh /vagrant/id_rsa.pub /vagrant/id_rsa
		chown -R vagrant:vagrant /home/vagrant/.ssh
		chmod 400 /home/vagrant/.ssh/id_rsa && chmod 644 /home/vagrant/.ssh/id_rsa.pub
        #mkdir -p ~root/.ssh
        #cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
  end

  config.vm.define "nginx" do |nfsc|
    nfsc.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
	nfsc.vm.provision "file", source: "id_rsa.pub", destination: "id_rsa.pub"
    nfsc.vm.hostname = "nginx"
    nfsc.vm.provision "shell", inline: <<-SHELL
		cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys		
        #mkdir -p ~root/.ssh
        #cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
  end

end